function [pmNormFeatures, pmNormFeatNames, measures] = createFullFeaturesAndLabelsFcn(pmRawMeasFeats, pmMSFeats, pmBuckMeasFeats, pmRangeFeats, pmVolFeats, ...
                pmAvgSegFeats, pmVolSegFeats, pmCChangeFeats, pmPMeanFeats, pmPStdFeats, ...
                pmBuckPMeanFeats, pmBuckPStdFeats, pmDateFeats, pmDemoFeats, featureparamsrow, measures, nmeasures)

% createFullFeaturesAndLabelsFcn - function to apply measures mask to base
% features and create the final normalised feature array

% set various variables
[featureduration, predictionduration, datefeat, nbuckets, navgseg, nvolseg, nbuckpmeas, ...
      nrawfeatures, nmsfeatures, nbucketfeatures, nrangefeatures, nvolfeatures, navgsegfeatures, ...
      nvolsegfeatures, ncchangefeatures, npmeanfeatures, npstdfeatures, ...
      nbuckpmeanfeatures, nbuckpstdfeatures, ndatefeatures, ndemofeatures] = ...
        setBaseNumMeasAndFeatures(featureparamsrow, nmeasures);

% set measures masks for the particular feature combination requested
fprintf('Setting measures masks for features\n');
[measures] = preprocessMeasuresMask(measures, nmeasures, featureparamsrow);
toc
fprintf('\n');

tic
fprintf('Extracting relevant features for measures\n');
rawmeasmask    = logical(duplicateMeasuresByFeatures(measures.RawMeas', featureduration, nmeasures));
msmeasmask     = logical(duplicateMeasuresByFeatures(measures.MSMeas', featureduration, nmeasures));
bucketmeasmask = logical(duplicateMeasuresByFeatures(measures.BucketMeas', featureduration * nbuckets, nmeasures));
rangemask      = logical(measures.Range');
volmask        = logical(duplicateMeasuresByFeatures(measures.Volatility', (featureduration - 1), nmeasures));
avgsegmask     = logical(duplicateMeasuresByFeatures(measures.AvgSeg', navgseg, nmeasures));
volsegmask     = logical(duplicateMeasuresByFeatures(measures.VolSeg', nvolseg, nmeasures));
cchangemask    = logical(measures.CChange');
pmeanmask      = logical(measures.PMean');
pstdmask       = logical(measures.PStd');
buckpmeanmask  = logical(duplicateMeasuresByFeatures(measures.BuckPMean', nbuckpmeas, nmeasures));
buckpstdmask   = logical(duplicateMeasuresByFeatures(measures.BuckPStd', nbuckpmeas, nmeasures));

ndatefeats = size(pmDateFeats,2);
if featureparamsrow.datefeat == 0
    datemask = false(1, ndatefeats);
else
    datemask = true(1, ndatefeats);
end

ndemofeats = size(pmDemoFeats,2);
if featureparamsrow.demofeat == 1
    demomask = false(1, ndemofeats);
elseif featureparamsrow.demofeat == 2
    demomask = true(1, ndemofeats);
else
    demomask = false(1, ndemofeats);
    demomask(featureparamsrow.demofeat - 2) = true;
end

pmNormFeatures = [pmRawMeasFeats(:, rawmeasmask), ...
                  pmMSFeats(:, msmeasmask), ...
                  pmBuckMeasFeats(:, bucketmeasmask), ...
                  pmRangeFeats(:, rangemask), ...
                  pmVolFeats(:, volmask), ...
                  pmAvgSegFeats(:, avgsegmask), ...
                  pmVolSegFeats(:, volsegmask), ...
                  pmCChangeFeats(:, cchangemask), ...
                  pmPMeanFeats(:, pmeanmask), ...
                  pmPStdFeats(:, pstdmask), ...
                  pmBuckPMeanFeats(:, buckpmeanmask), ...
                  pmBuckPStdFeats(:, buckpstdmask), ...
                  pmDateFeats(:, datemask), ...
                  pmDemoFeats(:, demomask)];

pmNormFeatNames = [reshape(cellstr(cellstr('RM-' + string(measures.ShortName(logical(measures.RawMeas)))    + '-') + string(featureduration:-1:1))',            [1 sum(measures.RawMeas)    * featureduration]           ), ...
                   reshape(cellstr(cellstr('MS-' + string(measures.ShortName(logical(measures.MSMeas)))     + '-') + string(featureduration:-1:1))',            [1 sum(measures.MSMeas)     * featureduration]           ), ...
                   reshape(cellstr(cellstr('BM-' + string(measures.ShortName(logical(measures.BucketMeas))) + '-') + string(featureduration * nbuckets:-1:1))', [1 sum(measures.BucketMeas) * featureduration * nbuckets]), ...
                   reshape(cellstr(cellstr('RA-' + string(measures.ShortName(logical(measures.Range)))      + '-') + string(1:-1:1))',                          [1 sum(measures.Range)      * 1]                         ), ...
                   reshape(cellstr(cellstr('VO-' + string(measures.ShortName(logical(measures.Volatility))) + '-') + string((featureduration - 1):-1:1))',      [1 sum(measures.Volatility) * (featureduration - 1)]     ), ...
                   reshape(cellstr(cellstr('AS-' + string(measures.ShortName(logical(measures.AvgSeg)))     + '-') + string(navgseg:-1:1))',                    [1 sum(measures.AvgSeg)     * navgseg]                   ), ...
                   reshape(cellstr(cellstr('VS-' + string(measures.ShortName(logical(measures.VolSeg)))     + '-') + string(nvolseg:-1:1))',                    [1 sum(measures.VolSeg)     * nvolseg]                   ), ...
                   reshape(        cellstr('CC-' + string(measures.ShortName(logical(measures.VolSeg)))     )',                                                 [1 sum(measures.VolSeg)]                                 ), ...
                   reshape(        cellstr('PM-' + string(measures.ShortName(logical(measures.PMean)))      )',                                                 [1 sum(measures.PMean)]                                  ), ...
                   reshape(        cellstr('PS-' + string(measures.ShortName(logical(measures.PStd)))       )',                                                 [1 sum(measures.PStd)]                                   ), ...
                   reshape(cellstr(cellstr('BP-' + string(measures.ShortName(logical(measures.BuckPMean)))  + '-') + string(nbuckpmeas:-1:1))',                 [1 sum(measures.BuckPMean)  * nbuckpmeas]                ), ...
                   reshape(cellstr(cellstr('BS-' + string(measures.ShortName(logical(measures.BuckPStd)))   + '-') + string(nbuckpmeas:-1:1))',                 [1 sum(measures.BuckPStd)   * nbuckpmeas]                ), ...
                   reshape(        cellstr('DA-'                                                            + string(sum(datemask):-1:1))',                     [1                            sum(datemask)]             ), ...
                   reshape(        cellstr('DE-'                                                            + string(sum(demomask):-1:1))',                     [1                            sum(demomask)]             )];


fprintf('%d missing data points in features\n', sum(sum((pmNormFeatures == featureparamsrow.msconst))));

end

