function [clPatient, clAdmissions, clAntibiotics, clClinicVisits, clOtherVisits, ...
    clCRP, clPFT, clMicrobiology, clHghtWght, clOthClinMeas, clEndStudy] = createClimbClinicalTables(nrows)

% createClimbClinicalTables - creates empty copies of all the clinical
% tables.

clPatient      = table('Size',[nrows 21], ...
    'VariableTypes', {'double',   'cell',   'cell', 'datetime', 'datetime', 'double',  'double', 'double', 'cell', ...
                      'double', 'double', 'double',   'double',     'cell',   'cell', 'double', ...
                      'double', 'double', 'double', 'double', 'double'}, ...
    'VariableNames', {'ID',   'Hospital',   'StudyNumber', 'StudyDate', 'DOB', 'Age',  'AgeYy', 'AgeMm', 'Sex', ...
                      'Height', 'Weight', 'PredictedFEV1', 'FEV1SetAs', 'TooYoung', 'StudyEmail', 'CalcAge', ...
                      'CalcAgeExact', 'CalcPredictedFEV1', 'CalcPredictedFEV1OrigAge', 'CalcFEV1SetAs', 'CalcFEV1SetAsOrigAge'});

clAdmissions   = table('Size',[nrows 6], ...
    'VariableTypes', {'double',    'cell',        'cell', 'datetime',  'datetime',   'cell'}, ...
    'VariableNames', {'ID',    'Hospital', 'StudyNumber', 'Admitted', 'Discharge', 'Reason'});

clAntibiotics  = table('Size',[nrows 9], ...
    'VariableTypes', {'double',    'cell',        'cell', 'cell',            'cell',     'cell', 'cell',   'datetime',  'datetime'}, ...
    'VariableNames', {'ID',    'Hospital', 'StudyNumber', 'AntibioticName', 'Route', 'HomeIV_s', 'Reason', 'StartDate',  'StopDate'});

clClinicVisits = table('Size',[nrows 4], ...
    'VariableTypes', {'double',    'cell',        'cell',       'datetime'}, ...
    'VariableNames', {'ID',    'Hospital', 'StudyNumber', 'AttendanceDate'});

clOtherVisits  = table('Size',[nrows 5], ...
    'VariableTypes', {'double',    'cell',        'cell',       'datetime',      'cell'}, ...
    'VariableNames', {'ID',    'Hospital', 'StudyNumber', 'AttendanceDate', 'VisitType'});

clPFT          = table('Size',[nrows 10], ...
    'VariableTypes', {'double',    'cell',        'cell',         'datetime', 'double', 'double', 'double', 'double', 'double',           'double'}, ...
    'VariableNames', {'ID',    'Hospital', 'StudyNumber', 'LungFunctionDate',   'FEV1',  'FEV1_',   'FVC1',  'FVC1_', 'CalcFEV1SetAs', 'CalcFEV1_'});

clCRP          = table('Size',[nrows 8], ...
    'VariableTypes', {'double',    'cell',        'cell', 'datetime',  'cell',  'cell',               'cell',       'double'}, ...
    'VariableNames', {'ID',    'Hospital', 'StudyNumber',  'CRPDate', 'Level', 'Units', 'PatientAntibiotics', 'NumericLevel'});

clMicrobiology = table('Size',[nrows 5], ...
    'VariableTypes', {'double',    'cell',        'cell',         'cell',         'datetime'}, ...
    'VariableNames', {'ID',    'Hospital', 'StudyNumber', 'Microbiology', 'DateMicrobiology'});

clHghtWght = table('Size',[nrows 9], ...
    'VariableTypes', {'double',    'cell',        'cell', 'datetime', 'double', 'double',   'double',   'double', 'double'}, ...
    'VariableNames', {'ID',    'Hospital', 'StudyNumber', 'MeasDate', 'Height', 'H_ZScore', 'Weight', 'W_ZScore',    'BMI'});

clOthClinMeas = table('Size',[nrows 8], ...
    'VariableTypes', {'double',    'cell',        'cell', 'datetime', 'double', 'double',   'double',   'double'}, ...
    'VariableNames', {'ID',    'Hospital', 'StudyNumber', 'MeasDate',     'HR',     'RR',     'Temp',   'O2_Sat'});

clEndStudy     = table('Size',[nrows 4], ...
    'VariableTypes', {'double',   'cell',        'cell',             'cell'}, ...
    'VariableNames', {'ID',   'Hospital', 'StudyNumber', 'EndOfStudyReason'});

end

