function [acphysdata] = createAceCFMeasuresTable(nrows)

% createAceCFMeasuresTable - creates a copy of the physdata
% measures table for the ACE-CF study with <nrows> blank rows in

acphysdata      = table('Size',[nrows 17], ...
    'VariableTypes', {'double',        'double',        'double',       'cell',       'cell',          'cell',          'datetime', ...
                      'double',        'double',        'double',       'double',     'double',        'double', ...
                      'double',        'double',        'double',       'double'}, ...
    'VariableNames', {'SmartCareID',   'ScaledDateNum', 'DateNum',      'UserName',   'RecordingType', 'CaptureType',   'Date_TimeRecorded', ...
                      'FEV',           'WeightInKg',    'O2Saturation', 'Pulse_BPM_', 'Temp_degC_',    'Calories', ...
                      'Rating',        'Sleep',         'HasCondition', 'CalcFEV1_'});

end

