function [mltable] = createBronchExSingleClinicalTable(mltablename, nrows)

% createBronchExSingleClinicalTable - creates a given clinical
% table for the BronchEx study, based on the name parameter, with the number
% of rows specified

switch mltablename
    case 'bePatient'
        mltable = table('Size',[nrows 27], ...
                        'VariableTypes', {'double',                   'cell',           'cell',                  'datetime',    'datetime',         'datetime',           ...
                                          'datetime',                 'datetime',       'double',                'cell',        'cell',             'double',             ...
                                          'double',                   'double',         'double',                'cell',        'cell',             'cell',               ...
                                          'datetime',                 'cell',           'double',                'double',      'double',           'double',             ...
                                          'double',                   'double',         'double'},                                                                        ...
                        'VariableNames', {'ID',                       'Hospital',       'StudyNumber',           'StudyDate',   'Prior6Mnth',       'Post6Mnth',          ...
                                          'PatClinDate',              'DOB',            'Age',                   'Sex',         'Ethnicity',        'Height',             ...
                                          'Weight',                   'PredictedFEV1',  'FEV1SetAs',             'StudyEmail',  'GeneralComments',  'ConsentStatus',      ...
                                          'ConsentDate',              'PartitionKey',   'StudyDays',             'CalcAge',     'CalcAgeExact',     'CalcPredictedFEV1',  ...
                                          'CalcPredictedFEV1OrigAge', 'CalcFEV1SetAs',  'CalcFEV1SetAsOrigAge'});
                                          
    
    case 'bePatDataUpdTo'
        mltable = table('Size', [nrows, 4], ...
                        'VariableTypes', {'double',  'cell',     'cell',         'datetime'}, ...
                        'VariableNames', {'ID',      'Hospital', 'StudyNumber',  'PatClinDate'});
    
    case 'beDrugTherapy'
        mltable = table('Size',[nrows 7], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime',             'datetime',            'cell',            'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'DrugTherapyStartDate', 'DrugTherapyStopDate', 'DrugTherapyType', 'DrugTherapyComment',});

    case 'beAdmissions'
        mltable = table('Size',[nrows 6], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime', 'datetime',  'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'Admitted', 'Discharge', 'Comments'});

    case 'beAntibiotics'
        mltable = table('Size',[nrows 15], ...
                        'VariableTypes', {'double',       'cell',      'cell',         'datetime',    'datetime',  'cell',            ...
                                          'cell',         'cell',      'cell',         'cell',        'cell',      'cell',            ...
                                          'cell',         'cell',      'cell'},                                                       ...
                        'VariableNames', {'ID',           'Hospital',  'StudyNumber',  'StartDate',   'StopDate',  'AntibioticName',  ...
                                          'OtherABName',  'DrugType',  'Route',        'OtherRoute',  'Reason',    'OtherReason',     ...
                                          'ProtocolDef',  'OtherDef',  'Comments'});
                  
    case 'beClinicVisits'
        mltable = table('Size',[nrows 9], ...
                        'VariableTypes', {'double',   'cell',       'cell',         'datetime',        'cell',     'cell',    ...
                                          'cell',     'cell',       'cell'},                                                  ...
                        'VariableNames', {'ID',       'Hospital',   'StudyNumber',  'AttendanceDate',  'EncType',  'UEType',  ...
                                          'OtherUE',  'EncReason',  'Comments'});

    case 'beOtherVisits' 
        mltable = table('Size',[nrows 6], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime',       'cell',      'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'AttendanceDate', 'VisitType', 'Comments'});

    case 'beUnplannedContact'
        mltable = table('Size',[nrows 6], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime',    'cell',          'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'ContactDate', 'TypeOfContact', 'Comments'});

    case 'bePFT' 
        mltable = table('Size',[nrows 7], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime',          'double',  'double',    'cell'},      ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'LungFunctionDate',  'FEV1',    'PredFEV1',  'Comments'});

    case 'beCRP'
        mltable = table('Size',[nrows 9], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime', 'double', 'cell',  'cell',               'double',       'cell'},     ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'CRPDate',  'Level',  'Units', 'PatientAntibiotics', 'NumericLevel', 'Comments'});

    case 'beMicrobiology'
        mltable = table('Size',[nrows 7], ...
                        'VariableTypes', {'double', 'cell',      'cell',         'cell',          'datetime',          'cell',        'cell'},      ...
                        'VariableNames', {'ID',     'Hospital',  'StudyNumber',  'Microbiology',  'DateMicrobiology',  'OtherMicro',  'Comments'});

    case 'beHghtWght'
        mltable = table('Size',[nrows 10], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime', 'double', 'double',   'double', 'double',   'double',  'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'MeasDate', 'Height', 'H_ZScore', 'Weight', 'W_ZScore', 'BMI',     'Comments'});

    case 'beEndStudy'
        mltable = table('Size',[nrows 4], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'EndOfStudyReason'});
    
    otherwise
        fprintf('**** Unknown table name ****');
        mltable = [];
        return;
end

end

