function [mltable] = createBreatheSingleClinicalTable(mltablename, nrows)

% createBreatheSingleClinicalTable - creates a given clinical
% table for project breathe, based on the name parameter, with the number
% of rows specified

switch mltablename
    case 'brPatient'

        mltable = table('Size',[nrows 30], ...
                        'VariableTypes', {'double',          'cell',        'cell',           'cell',               'datetime',     'datetime',     'datetime', ...
                                          'datetime',        'datetime',    'double',         'cell',               'double',       'double',  ...
                                          'double',          'double',      'cell',           'cell',               'cell',    ...
                                          'cell',            'double',      'double',         'double',             'double',       ...
                                          'double',          'double', ...
                                          'cell',            'datetime',    'datetime',       'cell',               'cell'}, ...
                        'VariableNames', {'ID',              'REDCapID',    'Hospital',       'StudyNumber',        'StudyDate',    'Prior6Mnth',   'Post6Mnth', ...
                                          'PatClinDate',     'DOB',         'Age',            'Sex',                'Height',       'Weight',  ...
                                          'PredictedFEV1',   'FEV1SetAs',   'StudyEmail',     'CFGene1',            'CFGene2', ...
                                          'GeneralComments', 'CalcAge',     'CalcAgeExact',   'CalcPredictedFEV1',  'CalcPredictedFEV1OrigAge', ...
                                          'CalcFEV1SetAs',   'CalcFEV1SetAsOrigAge', ...
                                          'ConsentStatus',   'ConsentDate', 'WithdrawalDate', 'WithdrawalComments', 'PartitionKey'});
    case 'brDrugTherapy'
        
        mltable = table('Size',[nrows 7], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime',             'datetime',             'cell',            'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'DrugTherapyStartDate', 'DrugTherapyStopDate', 'DrugTherapyType', 'DrugTherapyComment',});

    case 'brAdmissions'
        mltable = table('Size',[nrows 6], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime', 'datetime',  'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'Admitted', 'Discharge', 'Comments'});

    case 'brAntibiotics'
        mltable = table('Size',[nrows 10], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'cell',           'cell',  'cell',     'cell',     'datetime',   'datetime', 'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'AntibioticName', 'Route', 'HomeIV_s', 'Elective', 'StartDate',  'StopDate', 'Comments'});

    case 'brClinicVisits'
        mltable = table('Size',[nrows 6], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime',       'cell',     'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'AttendanceDate', 'Location', 'Comments'});

    case 'brOtherVisits'
        mltable = table('Size',[nrows 6], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime',       'cell',      'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'AttendanceDate', 'VisitType', 'Comments'});

    case 'brUnplannedContact'
        mltable = table('Size',[nrows 6], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime',    'cell',          'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'ContactDate', 'TypeOfContact', 'Comments'});

    case 'brPFT' 
        mltable = table('Size',[nrows 9], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime',         'double', 'cell',  'double', 'double',    'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'LungFunctionDate', 'FEV1',   'Units', 'FEV1_',  'CalcFEV1_', 'Comments'});

    case 'brCRP'
        mltable = table('Size',[nrows 9], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime', 'double', 'cell',  'cell',               'double',       'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'CRPDate',  'Level',  'Units', 'PatientAntibiotics', 'NumericLevel', 'Comments'});

    case 'brMicrobiology'
        mltable = table('Size',[nrows 7], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'cell',         'datetime',         'cell',        'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'Microbiology', 'DateMicrobiology', 'NameIfOther', 'Comments'});

    case 'brHghtWght'
        mltable = table('Size',[nrows 10], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'datetime', 'double', 'double',   'double', 'double',   'double',  'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'MeasDate', 'Height', 'H_ZScore', 'Weight', 'W_ZScore', 'BMI',     'Comments'});

    case 'brEndStudy'
        mltable = table('Size',[nrows 4], ...
                        'VariableTypes', {'double', 'cell',     'cell',        'cell'}, ...
                        'VariableNames', {'ID',     'Hospital', 'StudyNumber', 'EndOfStudyReason'});
    otherwise
        fprintf('**** Unknown table name ****');
        mltable = [];
        return;
end

end

