function [brphysdata] = createBreatheMeasuresTable(nrows)

% createBreatheMeasuresTable - creates a copy of the physdata
% measures table for project breathe with <nrows> blank rows in

brphysdata      = table('Size',[nrows 17], ...
    'VariableTypes', {'double',        'double',        'double',       'cell',       'cell',          'cell',          'datetime', ...
                      'double',        'double',        'double',       'double',     'double',        'double', ...
                      'double',        'double',        'double',       'double'}, ...
    'VariableNames', {'SmartCareID',   'ScaledDateNum', 'DateNum',      'UserName',   'RecordingType', 'CaptureType',   'Date_TimeRecorded', ...
                      'FEV',           'WeightInKg',    'O2Saturation', 'Pulse_BPM_', 'Temp_degC_',    'Calories', ...
                      'Rating',        'Sleep',         'HasCondition', 'CalcFEV1_'});

%brphysdata      = table('Size',[nrows 22], ...
%    'VariableTypes', {'double',          'double',        'double',       'cell',         'cell',          'datetime', ...
%                      'double',          'double',        'double',       'double',       'double',        'double', ...
%                      'double',          'double',        'double',       'double',       'double',        'double', ...
%                      'double',          'double',        'double',       'double'}, ...
%   'VariableNames', {'SmartCareID',     'ScaledDateNum', 'DateNum',      'UserName',     'RecordingType', 'Date_TimeRecorded', ...
%                      'FEV1',            'FEV2575',       'FEV075',       'FEV1DivFEV6',  'FEV6',          'WeightInKg', ...
%                      'O2Saturation',    'Pulse_BPM_',    'RestingHR',    'Temp_degC_',   'Calories',      'Rating', ...
%                      'TotalMinAsleep',  'TotalMinAwake', 'HasColdOrFlu', 'HasHayfever'});

end

