function plotOutlierDataPoints(ax, days, mdata, outliers, max_offset, align_wind, colour, linestyle, linewidth, marker, markersize, markerec, markerfc)

% plotDataOutliers - plots the outliers in the measurement data

tmpoutlieridx = logical(zeros(1, max_offset + align_wind - 1));
tmpoutlieridx(max_offset:max_offset + align_wind - 1) = logical(outliers);

% plot measurement data
line(ax, days(tmpoutlieridx), mdata(tmpoutlieridx), ...
    'Color', colour, ...
    'LineStyle', linestyle, ...
    'LineWidth', linewidth, ...
    'Marker', marker, ...
    'MarkerSize', markersize,...
    'MarkerEdgeColor', markerec, ...
    'MarkerFaceColor', markerfc);

noutliers = sum(outliers);

end

