function [measures] = sortMeasuresForPaper(study, measures)

% sortMeasuresForPaper - returns a sorted measures table in the order to
% display measures in paper

if ismember(study, {'SC'})
    measures = measures([find(ismember(measures.DisplayName,'LungFunction')), ...
                         find(ismember(measures.DisplayName,'O2Saturation')), ...
                         find(ismember(measures.DisplayName,'PulseRate')),    ...
                         find(ismember(measures.DisplayName,'Activity')),     ...
                         find(ismember(measures.DisplayName,'Weight')),       ...
                         find(ismember(measures.DisplayName,'Temperature')),  ...
                         find(ismember(measures.DisplayName,'Cough')),        ...
                         find(ismember(measures.DisplayName,'Wellness')),     ...
                         find(ismember(measures.DisplayName,'SleepActivity')) ], :);
elseif ismember(study, {'CL'})
    measures = measures([find(ismember(measures.DisplayName,'LungFunction')),     ...
                         find(ismember(measures.DisplayName,'O2Saturation')),     ...
                         find(ismember(measures.DisplayName,'PulseRate')),        ...
                         find(ismember(measures.DisplayName,'Activity')),         ...
                         find(ismember(measures.DisplayName,'Cough')),            ...
                         find(ismember(measures.DisplayName,'Wellness')),         ...
                         find(ismember(measures.DisplayName,'Appetite')),         ...
                         find(ismember(measures.DisplayName,'Breathlessness')),   ...
                         find(ismember(measures.DisplayName,'RespiratoryRate')),  ...
                         find(ismember(measures.DisplayName,'SleepActivity')),    ...
                         find(ismember(measures.DisplayName,'SleepDisturbance')), ...
                         find(ismember(measures.DisplayName,'SputumVolume')),     ...
                         find(ismember(measures.DisplayName,'Temperature')),      ...
                         find(ismember(measures.DisplayName,'Tiredness'))         ], :);
else
    fprintf('**** need to set sort order for study %s ****\n', study);
end
                         

end

